# Load the Rails application.
require_relative "application"

# Initialize the Rails application.
Rails.application.initialize!

# Getting rid of the default div field_with_errors generated by Rails in order for us to create our Custom Error Messsage.
ActionView::Base.field_error_proc = Proc.new do |html_tag, instance|
  html_tag.html_safe
end
